# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param thin the number of between-sample random numbers
#' @param N the length of chain
#' @param a parameter 
#' @param b parameter
#' @param n the number of samples
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#' gibbsC <- gibbs_sampleC(2000,1,4,50,10)
#' qqplot(gibbsC[,1],gibbsR[,1],pch=16,cex=0.7,main="compare x") 
#' abline(a=0,b=1,col = "blue")
#' }
#' @export
gibbs_sampleC <- function(N, a, b, n, thin) {
    .Call('_StatComp21082_gibbs_sampleC', PACKAGE = 'StatComp21082', N, a, b, n, thin)
}

